SELECT * FROM proyecto.tb_cat_proyectos;


INSERT INTO `proyecto`.`tb_desarrolladores`
(`ID_DESARROLLADOR`,
`NOMBRE_DESARROLLADOR`,
`NIT`,
`DIRECCION_EMPRESA`,
`CORREO_ELECTRONICO`,
`TELEFONO`)
VALUES
(1,
'ARQUITECTURA Y CONSTRUCCIÓN - INCISA',
98745612,
'Local 125, Zona 2 de Mixco Calzada Roosevelt Km. 15',
'corre1@gmail.com',
24433304);


INSERT INTO `proyecto`.`tb_desarrolladores`
(`ID_DESARROLLADOR`,
`NOMBRE_DESARROLLADOR`,
`NIT`,
`DIRECCION_EMPRESA`,
`CORREO_ELECTRONICO`,
`TELEFONO`)
VALUES
(2,
'ASFINTECO / PROYECA',
984156544,
'Local 134, Zona 5 de Mixco Km. 18',
'corre2@gmail.com',
24434304);


INSERT INTO `proyecto`.`tb_desarrolladores`
(`ID_DESARROLLADOR`,
`NOMBRE_DESARROLLADOR`,
`NIT`,
`DIRECCION_EMPRESA`,
`CORREO_ELECTRONICO`,
`TELEFONO`)
VALUES
(3,
'COMPAÑÍA HARBOR',
845545261,
'Jutiapa, Jutiapa',
'correo3@gmail.com',
24304312);


